#!/usr/bin/env bash
#
# Alias for gradlew.  Used for development.  It starts
# the gradle daemon which should only be used
# when developing.
#
# Example:  ./gw clean build -x test
#
# Make script executable: chmod +x gw
#

export SPRING_CONFIG_LOCATION=${HOME}/smarter_app/security/ap-iat/ap-iat-security.yml

export SAML_KS_FILE=file:${HOME}/smarter_app/security/ap-iat/ap-iat-ui.jks

./gradlew --daemon $@
