# ---------------------------------------------------------
# The Gradle build expands its project properties to
# replace the substitution tokens.
# ---------------------------------------------------------

# shown on actuator '/info' endpoint
info:
  app:
    name: ${name}
    version: ${version}
    description: ${description}
    java:
      source: ${sourceCompatibility}
      target: ${targetCompatibility}

# actuator endpoints
management:
  context-path: "/manage"

api:
  context-path: "/api"
